### ISSUE TITLE
Should be upgraded to x64 platform

### ISSUE THREAD

**Issue by zhouxs1023** [stanekTM/PCB_Elegance#1]
At present, this project can only compile to Win32, not x64. Is there a plan to  upgrade to x64 bit platform？

**Comment by stanekTM** [comment]
Hi, I haven't researched how to switch to x64 yet and what steps I should take. I use it as it is so far. Do you have an idea?

**Comment by zhouxs1023** [comment]
At the moment, I don't have any good suggestions. I just hope to support x64 bit and have a more modern UI.

**Comment by stanekTM** [comment]
Looking at the official site, it looks like the code is no longer being developed by Tim Worthington. Unfortunately, I am busy with my own development of the micro RC RX and time does not allow me to take a closer look at x64.
I have already stopped testing on XP and I only use the program on W10. If you come up with a solution, do not hesitate to contact me.

**Comment by zhouxs1023** [comment]
OK,Thank you very much!
