### ISSUE TITLE
sch editor can not open compmenu.txt

### ISSUE THREAD

**Issue by zhouxs1023** [stanekTM/PCB_Elegance#2]
I downloaded lastest source,open  PCB_Elegance\PCB_Elegance_v3.52.1\design.exe, open projects files, then open schematic editor but  sch editor can not open compmenu.txt on window7 as below:

![1](https://user-images.githubusercontent.com/905931/106157739-f9a53880-61bd-11eb-91f7-cebdf8c72bef.PNG)
then turn on:
![2](https://user-images.githubusercontent.com/905931/106157924-29544080-61be-11eb-954d-c0131953fafb.PNG)

**Comment by stanekTM** [comment]
Hi,
for some reason Github did not upload the "shapes" sample project files. I will look at it.

**Comment by stanekTM** [comment]
I uploaded new sample projects and everything looks fine for me.

I think you have a nested folder too far away.

Try something like this "C:\GitHub\PCB_Elegance"

**Comment by stanekTM** [comment]
I uploaded new sample projects and everything looks fine for me, try to download the project again.
What does it tell you in "Design manager" -> "Configure the project paths" ?

Start the "Design manager" as an administrator, in your case change the address "D:\360Downloads\PCB_Elegance\PCB_Elegance_v3.52.1\projects", "Set" and "OK" button and everything should be fine.

![path](https://user-images.githubusercontent.com/44894972/106180297-69a2c700-619c-11eb-9d7a-fe65d6c2a39d.PNG)

**Comment by zhouxs1023** [comment]
The problem has been solved.Thanks for your reply.
