### ISSUE TITLE
how  to generate  comp.txt  and compmenu.txt  files?

### ISSUE THREAD

**Issue by zhouxs1023** [stanekTM/PCB_Elegance#3]
I had compiled  source code successfully,but  I  don't know how  to generate comp.txt  and compmenu.txt  files?
I hope you will help me find the answer.

**Comment by stanekTM** [comment]
I do not use this function, it is not generated, it is loaded as a part of "Add components from database". Can be edited with a text editor.

![a](https://user-images.githubusercontent.com/44894972/106319117-3bdb8200-6271-11eb-82d5-51869a602eb1.PNG)

![b](https://user-images.githubusercontent.com/44894972/106319134-3f6f0900-6271-11eb-9d19-b0e06abe279e.PNG)

**Comment by zhouxs1023** [comment]
If there is no comp.txt and compmenu.txt, the database will have no components list  as  below
![IMG_20210130_053528](https://user-images.githubusercontent.com/905931/106330213-cb0e8700-62bd-11eb-8902-c462991b0234.png)

comp.txt and compmenu.txt  needs to be added manually  with a text editor？

**Comment by stanekTM** [comment]
These ".TXT" files are already part of the "projects" folder. There is no reason to generate them, just in case you want to change the language. I haven't explored them in more detail, I don't use a library and I create "symbols" and "shapes" individually for my needs where I can do with the basic components.

![ad](https://user-images.githubusercontent.com/44894972/106340112-064a8f00-6299-11eb-957e-2f4d180c3aa9.PNG)

![b](https://user-images.githubusercontent.com/44894972/106340114-06e32580-6299-11eb-9d2f-546c2b91cc19.PNG)

**Comment by stanekTM** [comment]
If you are compiling the program, you definitely want to improve it and run it from the "debug" folder, then I recommend adding the necessary files from the "PCB_Eleg .." folder. I tested on W10 and no problem.

![f](https://user-images.githubusercontent.com/44894972/106340973-d650bb00-629b-11eb-9039-054499e345a9.PNG)

**Comment by zhouxs1023** [comment]
Thank you very much for your explanation！I had known

**Comment by stanekTM** [comment]
Unfortunately, these tools are no longer evolving, this is the only thread mentioned

https://www.eevblog.com/forum/eda/pcb-elegance-new-version/

My pitbucket repair calls were never answered, so I set out on my own. The program code is extensive, so when designing a PCB, when I encounter errors or what could be improved, I solve the problem. There are many functions that I do not use even in the production of PCBs and they could be removed. For now, however, I leave these functions to others if they are interested. I am a beginner in "C" and I have many other projects. I would like to know how many users are PCB_Eleg .. I will monitor your changes, do not hesitate to improve the code. This project is more for fans of "C".
