### ISSUE TITLE
Should add language set

### ISSUE THREAD

**Issue by zhouxs1023** [stanekTM/PCB_Elegance#4]
Language path setting function can be added
![add language set](https://user-images.githubusercontent.com/905931/110618628-e3819380-81d1-11eb-9057-36d7a5a9680c.png)

**Comment by stanekTM** [comment]
Great, have you implemented this path?
Do you want me to include your changes?

**Comment by zhouxs1023** [comment]
This function  suddenly occurred to me, and I didn't realize it. Now I are trying to compile it on win64 system,but have some bugs!

**Comment by stanekTM** [comment]
Okay, I'll track your accomplishments.

**Comment by stanekTM** [comment]
Hi, what are you compiling the project on?
Unfortunately, I did not try an IDE other than Visual Studio.

**Comment by zhouxs1023** [comment]
Unfortunately, I don't have a way to solve the problem of loading symbol table. I'm asking tycz (on the forum) oneevblog.com, But he hasn't answered me yet!

**Comment by stanekTM** [comment]
Hi, added "Discussion" option in Github. This spreadsheet?

![a](https://user-images.githubusercontent.com/44894972/112635300-f0da8700-8e3b-11eb-8f89-8565f7626cda.PNG)

or

![b](https://user-images.githubusercontent.com/44894972/112635322-f59f3b00-8e3b-11eb-87f7-d1770bd8f999.PNG)

**Comment by zhouxs1023** [comment]
I have uploaded it to GitHub（https://github.com/zhouxs1023/PCB_Elegance）. Now 32bit and 64bit can be compiled successfully, but there are some bugs in 64 bit . Click Schematic editor and layout editor, then the missing part message will appear, as shown in the figure below
![sch](https://user-images.githubusercontent.com/905931/112661475-85bb9f80-8e91-11eb-9da7-006724002571.PNG)
![pcb](https://user-images.githubusercontent.com/905931/112661523-9409bb80-8e91-11eb-9ca9-d4278caee88a.PNG)

**Comment by stanekTM** [comment]
That's great, I'll test. I looked at the changes you are compiling for W8.1 64bit? For the sake of order, I will have to delete the comments in my native language and replace them with English.
Thanks, this program deserves attention and fixes and updates.
I just got a printed circuit board from JLCPCB with a Elegance Gerber PCB and they are absolutely fine.

**Comment by zhouxs1023** [comment]
After I reset the configure path for projects,,the loading symbol will be normal, and the port  x64 should be OK!

**Comment by stanekTM** [comment]
I switched targeting to W10 and everything looks good.

`<WindowsTargetPlatformVersion>10.0.19041.0</WindowsTargetPlatformVersion>`

Thank you very much @zhouxs1023

**Comment by zhouxs1023** [comment]
That's good. I'll try add language settings later！

**Comment by stanekTM** [comment]
That's great, thank you. Unfortunately, I'm busy with another project and a new job. As soon as I can, they start working to fix the visibility of the "silscreen", which becomes invisible when it is created.

Sincerely, Jiří

**Comment by zhouxs1023** [comment]
I have finished language path set on vs2015 successfully,
pls clone source to compile on windows10, if compiler successfully,I will PR 
source: https://github.com/zhouxs1023/PCB_Elegance

**Comment by stanekTM** [comment]
Initial testing on W10 was successful. I've already merged your changes, moved the translations folder, added a description.
I think I can close this as a problem.

Thank you very much Jiří
